<a href="https://colab.research.google.com/github/Lalitmohan6376/Deep-Learning/blob/main/DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
# UNIt-1

In [3]:
# tf.constant()

a = tf.constant([1,2,3])
print(a)
b = tf.constant(5)
print(b)
c = tf.constant([[1,2],[3,4]])
print(c)
try:
  c[0] = 10
except:
  print("Error")

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Error


In [4]:
#tf.variable()
a = tf.Variable([1,2,3])
try:
  a.assign([4,5,6])
except:
  print("Error")

print(a)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>


In [5]:
# tf.zeros(), tf.ones(),tf.random.normal()
a = tf.zeros((2,3))
print(a)

b = tf.ones((2,3))
print(b)

c = tf.random.normal((2,3))
print(c)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-0.9782324  -1.4421045  -0.68393135]
 [-0.43223324 -0.551867   -0.94325894]], shape=(2, 3), dtype=float32)


In [6]:
# tf.reshape()
a = tf.constant([1,2,3,4])
b = tf.reshape(a,(2,2))
print(b)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [7]:
# tf.matmul()
A = tf.constant([[1,2],[3,4]])
B = tf.constant([[5,6],[7,8]])
C = tf.matmul(A,B)
print(C)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [8]:
# tf.reduce_mean()

a = tf.constant([10,20,30,40])
mean = tf.reduce_mean(a)
print(mean)

tf.Tensor(25, shape=(), dtype=int32)


In [9]:
# UNIT-2

In [10]:
# tf.data.Dataset.from_tensor_slices()
# convert data into tensorflow dataset

data = [10,20,30,40]
dataset = tf.data.Dataset.from_tensor_slices(data)
for i in dataset:
  print(i)

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(20, shape=(), dtype=int32)
tf.Tensor(30, shape=(), dtype=int32)
tf.Tensor(40, shape=(), dtype=int32)


In [11]:
# Dataset.batch()
# Divide a dataset into small groups called batches.
data = [1,2,3,4,5,6,7,8,9,10]
dataset = tf.data.Dataset.from_tensor_slices(data)
dataset = dataset.batch(2)
for batch in dataset:
  print(batch)

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)
tf.Tensor([7 8], shape=(2,), dtype=int32)
tf.Tensor([ 9 10], shape=(2,), dtype=int32)


In [12]:
# Dataset.shuffle()
# Is used to randomly shuffle the data in dataset.

data = [10,20,30,40,50,60]
dataset = tf.data.Dataset.from_tensor_slices(data)
dataset = dataset.shuffle(6).batch(2)
for i in dataset:
  print(i)

tf.Tensor([10 30], shape=(2,), dtype=int32)
tf.Tensor([20 50], shape=(2,), dtype=int32)
tf.Tensor([60 40], shape=(2,), dtype=int32)


In [13]:
# dataset.map()
# Is used to apply a function to every element of a dataset.
data = [1,2,3,4,5]
dataset = tf.data.Dataset.from_tensor_slices(data)
data = dataset.map(lambda x: x*2)
for i in data:
  print(i)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


In [14]:
# Sequential()

model = Sequential([
Dense(64),
Dense(64),
Dense(1)
 ])

In [15]:
from tensorflow.keras.layers import Input,Dense
from tensorflow.keras.models import Model
inputs = Input(shape=(4,))
x = Dense(32,activation='relu')(inputs)
branch1 = Dense(16,activation='relu')(x)
branch2 = Dense(16,activation='relu')(x)
combined = Dense(8,activation='relu')(branch1 + branch2)
output = Dense(1)(combined)
model = Model(inputs=inputs,outputs=output)
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 4)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 32)        │        160 │ input_layer[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 16)        │        528 │ dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 16)        │        528 │ dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add (Add)           │ (None, 16)        │          0 │ dense_4[0][0],    │
│                     │                   │            │ dense_5[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_6 (Dense)     │ (None, 8)         │        136 │ add[0][0]         │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_7 (Dense)     │ (None, 1)         │          9 │ dense_6[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 1,361 (5.32 KB)

 Trainable params: 1,361 (5.32 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
# RelU

from tensorflow.keras.layers import ReLU
# model = Sequential([
#     Dense(64,activation='relu'),
#     Dense(64,activation='relu'),
#     Dense(1)
#     ])
relu = ReLU()
x = tf.constant([-3,-1,2,5])
print(relu(x))

tf.Tensor([0 0 2 5], shape=(4,), dtype=int32)


In [17]:
# Flatten

from tensorflow.keras.layers import Flatten
flatten = Flatten()
x = tf.constant([[[1,2],[3,4]]])
print(flatten(x))

tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)


In [18]:
# Dropout

from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
Dropout(0.5)
model = Sequential([
    Dense(128,activation='relu'),
    Dropout(0.5),
    Dense(64,activation='relu'),
    Dense(1)
])

In [19]:
# Conv2D

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D

model = Sequential([
    Conv2D(32,(3,3),activation='relu',
           input_shape=(28,28,1))
])

model.summary()


/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 26, 26, 32)     │           320 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 320 (1.25 KB)

 Trainable params: 320 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D

model = Sequential([
    Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)),
    MaxPooling2D(pool_size=(2,2)),
    Flatten(),
    Dense(64,activation='relu'),
    Dense(10,activation='softmax')
])
model.summary()


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_1 (Conv2D)               │ (None, 26, 26, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 13, 13, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 5408)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 64)             │       346,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 347,146 (1.32 MB)

 Trainable params: 347,146 (1.32 MB)

 Non-trainable params: 0 (0.00 B)

In [21]:
from tensorflow.keras.layers import LSTM,Dense
from tensorflow.keras.models import Sequential

model = Sequential([
    LSTM(64,input_shape=(10,5)),
    Dense(1)
])
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 64)             │        17,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,985 (70.25 KB)

 Trainable params: 17,985 (70.25 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
import tensorflow as tf
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(64, activation='relu',input_shape=(10,)),
    Dense(1)
])
model.compile(
    optimizer='adam',
    loss = tf.keras.losses.MeanSquaredError()
)
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_14 (Dense)                │ (None, 64)             │           704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 769 (3.00 KB)

 Trainable params: 769 (3.00 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# model

model = Sequential([
    Dense(64, activation='relu', input_shape=(10,)),
    Dense(1, activation='sigmoid')
])

# compile

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_16 (Dense)                │ (None, 64)             │           704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 769 (3.00 KB)

 Trainable params: 769 (3.00 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(128, activation='relu', input_shape=(20,)),
    Dense(64, activation='relu'),
    Dense(3, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_18 (Dense)                │ (None, 128)            │         2,688 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 3)              │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,139 (43.51 KB)

 Trainable params: 11,139 (43.51 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
X = tf.constant([
    [1,2,3,4,5,6,7,8,9,10],
    [2,3,4,5,6,7,8,9,10,11],
    [3,4,5,6,7,8,9,10,11,12],
    [4,5,6,7,8,9,10,11,12,13]
],dtype=tf.float32)

y = tf.constant([
    [100],
    [150],
    [200],
    [250]
],dtype=tf.float32)


X_test = tf.constant([
    [5,6,7,8,9,10,11,12,13,14]
],dtype=tf.float32)

y_test = tf.constant([
    [300]
],dtype=tf.float32)

model = Sequential([
    Dense(64,activation='relu',input_shape=(10,)),
    Dense(1)
])

model.compile(optimizer='adam',
              loss = 'mse',
              metrics=['accuracy']
              )

model.fit(X,y,epochs=10)
model.evaluate(X_test,y_test)
model.predict(X_test)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.0000e+00 - loss: 34611.8516
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.0000e+00 - loss: 34465.0352
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.0000e+00 - loss: 34323.5000
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.0000e+00 - loss: 34182.9688
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.0000e+00 - loss: 34042.0430
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.0000e+00 - loss: 33901.0898
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.0000e+00 - loss: 33760.1562
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.0000e+00 - loss: 33619.2734
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.0000e+00 - loss: 33478.4414
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.0000e+00 - loss: 33337.0117
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 262ms/step - accuracy: 0.0000e+00 - loss: 88851.1172
1/1 ━━━━━━

array([[1.9209464]], dtype=float32)

In [26]:
from tensorflow.keras.callbacks import EarlyStopping
early = EarlyStopping(monitor='loss',
                      patience=2)

model.fit(X,y,epochs=5,callbacks=[early])

Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.0000e+00 - loss: 33195.4805
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.0000e+00 - loss: 33053.9453
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.0000e+00 - loss: 32912.1445
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.0000e+00 - loss: 32769.3750
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.0000e+00 - loss: 32626.5078


In [27]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [28]:
df = pd.read_csv("house_price_dataset_500_rows.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'house_price_dataset_500_rows.csv'

In [ ]:
df.columns


In [ ]:
X = df[["size_sqft","bedrooms","bathrooms","age_years","location_score"]]
y = df["price"]

In [ ]:
X_train,X_temp,y_train,y_temp = train_test_split(X,y,test_size=0.2)
X_val,X_test,y_val,y_test = train_test_split(X_temp,y_temp,test_size=0.5)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

model = Sequential([
    Dense(32,activation='relu',input_shape=(5,)),
    Dense(16,activation='relu'),
    Dense(1)
])

early_stop = EarlyStopping(patience=5)

In [ ]:
model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

In [ ]:
model.fit(X_train,y_train,epochs=50,validation_data=(X_val,y_val),callbacks=[early_stop])

In [ ]:
model.evaluate(X_test,y_test)

In [ ]:
import numpy as np
new_house = np.array([[1600, 3, 2, 6, 8]])
predicted_price = model.predict(new_house)
print(predicted_price)